# Generated by Django 3.1.4 on 2021-06-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dis',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
    ]
