# Generated by Django 3.1.4 on 2021-06-24 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
